### ISSUE TITLE
Forgets Background Opacity setting

### ISSUE THREAD

**Issue by dpriedel** [ddterm/gnome-shell-extension-ddterm#569] opened 2023-09-27 20:59 UTC
### GNOME Shell version

44.5

### Session type

Wayland (`echo $WAYLAND_DISPLAY` output is non-empty)

### Special configuration

- [ ] High DPI
- [ ] More than one monitor

### ddterm version

45

### Linux distro

Manjaro

### ddterm settings dump

[/]
background-opacity=0.70999999999999996
custom-font='Iosevka Term SS04 13'
ddterm-toggle-hotkey=['<Control><Alt>t']
hide-when-focus-lost=true
palette=['rgb(23,20,33)', 'rgb(192,28,40)', 'rgb(38,162,105)', 'rgb(162,115,76)', 'rgb(18,72,139)', 'rgb(163,71,186)', 'rgb(42,161,179)', 'rgb(208,207,204)', 'rgb(94,92,100)', 'rgb(246,97,81)', 'rgb(51,218,122)', 'rgb(233,173,12)', 'rgb(42,123,222)', 'rgb(192,97,203)', 'rgb(51,199,222)', 'rgb(255,255,255)']
panel-icon-type='none'
scroll-on-output=true
shortcuts-enabled=false
tab-policy='automatic'
use-system-font=false
window-maximize=false
window-monitor='focus'
window-size=0.40000000000000002
window-stick=false

### Description

Upon restarting my gnome session, background opacity is reset to 100% from what I have it set to.

When I open preferences:colors and 'wiggle' the background opacity setting, the opacity behaves as expected for the rest of my gnome session.

**Comment by amezin** [comment] 2023-09-28 07:45
So this only happens if you restart the session?

What happens if you just close all tabs in ddterm window, and then open it again?

**Comment by dpriedel** [comment] 2023-09-29 17:39
> So this only happens if you restart the session?
> 
> What happens if you just close all tabs in ddterm window, and then open it again?

When I said 'session', I meant gnome session.  When I close the ddterm window and reopen it in the same gnome sesson , it retains the opacity setting.

**Comment by amezin** [comment] 2023-09-30 07:51
Does it still happen if you uncheck "Use colors from system theme" in Preferences->Colors?

**Comment by amezin** [comment] 2023-09-30 09:09
[ddterm@amezin.github.com.shell-extension.zip](https://github.com/ddterm/gnome-shell-extension-ddterm/files/12774329/ddterm%40amezin.github.com.shell-extension.zip)

Does this build fix the issue?

**Comment by dpriedel** [comment] 2023-09-30 13:50
Yes.  This fixes the problem.


Thanks !!

**Comment by amezin** [comment] 2023-09-30 16:53
Then it's a duplicate of https://github.com/ddterm/gnome-shell-extension-ddterm/issues/570

**Closed by amezin** 2023-09-30 16:53 UTC
Labels: bug
