### ISSUE TITLE
can't hide the drop-down window by Shortcuts in gnome 47 beta

### ISSUE THREAD

**Issue by yuhldr** [ddterm/gnome-shell-extension-ddterm#1016] opened 2024-08-24 06:14 UTC
### GNOME Shell version

GNOME Shell 47.beta

### Linux distro

Arch Linux

### ddterm version

ddterm 53 revision e21859c5431c36687018ba67c033060c00094be7
Extension 53 revision e21859c5431c36687018ba67c033060c00094be7

### Session type

Wayland (`echo $WAYLAND_DISPLAY` output is non-empty)

### Special configuration

- [X] High DPI
- [ ] More than one monitor

### All installed extensions

```Text
It would also be wrong to keep this as well
```

### ddterm settings dump

```ini
[/]
custom-font='MesloLGS NF 10'
ddterm-activate-hotkey=@as []
ddterm-toggle-hotkey=['<Alt>s']
notebook-border=false
panel-icon-type='menu-button'
shortcut-window-hide=@as []
shortcuts-enabled=true
tab-expand=false
tab-label-ellipsize-mode='end'
tab-label-width=0.14999999999999999
tab-position='left'
use-system-font=false
window-maximize=false
```

### Description

in archlinux-gnome-47.beta by gnome-unstable

In the above settings, especially this setting panel-icon-type='menu-button', after opening the window with the shortcut key alt-s, it cannot be hidden, and you can see that the drop-down window pops up immediately after it is hidden. 

If you want to turn it off, you can only manually turn off the display button in the menu, and then use the shortcut alt-s

This setting "panel-icon-type='none'" problem will go away

**Comment by yuhldr** [comment] 2024-08-24 06:22
I edit metadata.json 
```json
{
  "shell-version": ["45", "46", "47"],
}
```
so can use in gnome47.beta

**Comment by razielanarki** [comment] 2024-08-24 07:28
i can confirm: (gnome 47-alpha on ubuntu 24.10.dev)

any setting for `panel-icon-type` that has a "menu-button" in it breaks the toggle show/hide logic either via hotkey, or dbus / gapplication fails 

i can toggle with `panel-icon-type` set `toggle-button` but not with `menu-button` and `toggle-and-menu-button`  (havent tested with `none`)

**Comment by amezin** [comment] 2024-08-24 20:38
Likely related to this https://gjs.guide/extensions/upgrading/gnome-shell-47.html#popupbasemenuitem

I'll wait for GNOME release candidate before doing anything for new version compatibility. Previously they broke the API I relied on in 46.rc: https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/3173

**Comment by razielanarki** [comment] 2024-08-25 23:53
> ... Previously they broke the API ...

Yeah, that seems to be a recurring pattern, sadly 
(v47 removed `Clutter.Color` and merged the functionality into `Cogl.Color`, breaking quite a few ext-s)

**Closed** 2024-09-18 14:05 UTC
Labels: bug

**Comment by amezin** [comment] 2024-09-18 14:07
Please try the current `master` (https://github.com/ddterm/gnome-shell-extension-ddterm/commit/695c1646e1fca18c3efe28a01ffcd0cc6df07e75)
