### ISSUE TITLE
Dark mode broken in GNOME 45.3

### ISSUE THREAD

**Issue by eddie-dunn** [ddterm/gnome-shell-extension-ddterm#750] opened 2024-01-17 16:06 UTC
### GNOME Shell version

GNOME Shell 45.3

### Session type

Wayland (`echo $WAYLAND_DISPLAY` output is non-empty)

### Special configuration

- [X] High DPI
- [X] More than one monitor

### Extension version

49

### Linux distro

"Fedora Linux 39.20240116.0 (Silverblue)"

### Verbose version information

```
ddterm 49 revision 73297878ac855f764e27fc2f31886c018419d34d
Extension 49 revision 73297878ac855f764e27fc2f31886c018419d34d
```

### ddterm settings dump

```ini
[/]
background-color='rgb(23,20,33)'
ddterm-toggle-hotkey=['F1']
foreground-color='rgb(208,207,204)'
hide-animation='linear'
hide-animation-duration=0.28000000000000003
hide-when-focus-lost=true
new-tab-button=true
notebook-border=true
override-window-animation=true
palette=['rgb(23,20,33)', 'rgb(192,28,40)', 'rgb(38,162,105)', 'rgb(162,115,76)', 'rgb(18,72,139)', 'rgb(163,71,186)', 'rgb(42,161,179)', 'rgb(208,207,204)', 'rgb(94,92,100)', 'rgb(246,97,81)', 'rgb(51,209,122)', 'rgb(233,173,12)', 'rgb(42,123,222)', 'rgb(192,97,203)', 'rgb(51,199,222)', 'rgb(255,255,255)']
panel-icon-type='toggle-and-menu-button'
shortcut-win-new-tab=['<Primary><Shift>t']
show-animation='linear'
tab-policy='automatic'
theme-variant='dark'
transparent-background=false
use-theme-colors=true
window-maximize=false
window-position='top'
window-size=0.70000000000000007

```

### Description

Dark mode broke for me after upgrading to GNOME 45.3/Fedora 39.

![Screenshot from 2024-01-17 17-00-23](https://github.com/ddterm/gnome-shell-extension-ddterm/assets/219063/25763682-15f8-44e1-83a1-2a30bd10a1f7)

**Comment by amezin** [comment] 2024-01-17 16:17
Yes, it's already fixed in the `master` branch, but I haven't made a release yet.

**Comment by eddie-dunn** [comment] 2024-01-17 16:20
Good to know, thanks :+1: 

For now, my workaround is to set `Legacy Applications` to `HighContrastInverse` (the only GTK3 dark theme I have available) via Gnome Tweaks.

I guess I should close this, then?

**Comment by amezin** [comment] 2024-01-18 06:09
Duplicate of https://github.com/ddterm/gnome-shell-extension-ddterm/issues/731

**Closed by amezin** 2024-01-18 06:09 UTC
Labels: bug

**Comment by amezin** [comment] 2024-01-18 07:49
By the way, can't you just set "Colors" -> "Theme Variant" to "Dark"?

**Comment by amezin** [comment] 2024-01-18 19:55
Fixed in v50

**Comment by eddie-dunn** [comment] 2024-01-24 15:48
> By the way, can't you just set "Colors" -> "Theme Variant" to "Dark"?
> 
> UPD: Oh, I see, it doesn't.

ddterm worked fine before I upgraded to Fedora 39 -- I suspect they removed the fallback dark mode theme that was previously used by ddterm. :shrug:

**Comment by amezin** [comment] 2024-01-24 16:21
Previously, it was enough to set [`gtk-application-prefer-dark-theme`](https://gjs-docs.gnome.org/gtk30~3.0/gtk.settings#property-gtk_application_prefer_dark_theme) setting to `true` to get dark theme. With GNOME 45, it silently stopped working. But ONLY for Adwaita theme. I'm using Arc theme, so I didn't notice it.
