### ISSUE TITLE
Margin around terminal

### ISSUE THREAD

**Issue by czQery** [ddterm/gnome-shell-extension-ddterm#975] opened 2024-06-29 08:42 UTC
I have floating bar with space around, so i would appreciate option to add margin around the terminal, or at least on sides.

![Screenshot from 2024-06-29 10-36-41](https://github.com/ddterm/gnome-shell-extension-ddterm/assets/60880179/80a2751e-1cae-4d72-8096-654c4de9ef2a)

**Comment by amezin** [comment] 2024-07-04 13:41
"Margin on the sides" is essentially the same as "configurable width".

So it's a duplicate of https://github.com/ddterm/gnome-shell-extension-ddterm/issues/129

Unlikely to be possible anytime soon, sorry

**Closed by amezin** 2024-07-04 13:41 UTC
Labels: enhancement
