### ISSUE TITLE
Strange laggy/glitchy show animation 

### ISSUE THREAD

**Issue by MatthewScholefield** [ddterm/gnome-shell-extension-ddterm#437] opened 2023-04-29 04:06 UTC
### GNOME Shell version

42.5

### Session type

Wayland (`echo $WAYLAND_DISPLAY` output is non-empty)

### Special configuration

- [X] High DPI
- [ ] More than one monitor

### ddterm version

43

### Linux distro

"Pop!_OS 22.04 LTS"

### ddterm settings dump

```
[/]
audible-bell=false
hide-animation='linear'
hide-animation-duration=0.070000000000000007
hide-when-focus-lost=true
override-window-animation=false
palette=['rgb(23,20,33)', 'rgb(192,28,40)', 'rgb(38,162,105)', 'rgb(162,115,76)', 'rgb(18,72,139)', 'rgb(163,71,186)', 'rgb(42,161,179)', 'rgb(208,207,204)', 'rgb(94,92,100)', 'rgb(246,97,81)', 'rgb(51,218,122)', 'rgb(233,173,12)', 'rgb(42,123,222)', 'rgb(192,97,203)', 'rgb(51,199,222)', 'rgb(255,255,255)']
scrollback-lines=10000000
shortcut-win-new-tab-after-current=['<Primary><Shift>t']
shortcut-window-hide=['<Primary>F12']
show-animation='linear'
show-animation-duration=0.13
show-scrollbar=false
tab-policy='never'
transparent-background=false
window-above=true
window-maximize=false
window-monitor='current'
window-position='top'
window-resizable=false
window-size=0.55000000000000004
window-skip-taskbar=true
window-type-hint='normal'
```

## Description

For some reason, sometimes the show animation will be very laggy/broken:

[ddterm-bug.webm](https://user-images.githubusercontent.com/5875019/235282691-87c801e5-546f-4649-9fef-0b135246d531.webm)

Occasionally the mini version that spawns at the start will be shifted to the left, and occasionally it will be towards the bottom left. Then randomly a few minute later it will be back to normal.

I have fractional scaling enabled with Wayland in case that is related.

**Observation:** I noticed that if I click and hold alt immediately after pressing the dropdown trigger it causes the window to flicker into a weird position momentarily similarly to the artifact observed in the video (but much briefer and in a slightly different position).

 - This occurs only when the window in focus beforehand is gnome-terminal or nautilus; not Firefox
 - For a little bit after doing this, the animation seems to have some minor artifacts

## Additional Info

Two of these lines appear in `journalctl -b` every time I open the dropdown:
```
Apr 28 20:40:41 pop-os gnome-shell[19466]: meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed
Apr 28 20:40:41 pop-os gnome-shell[19466]: meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed
```

**Comment by amezin** [comment] 2023-05-03 10:38
Do you have any other extensions installed? Especially something that animates/moves windows?

> I have fractional scaling enabled with Wayland in case that is related.

I've never tested fractional scaling, so yes, it may (likely) be the cause. Could you check if the problem is still present without fractional scaling?

**Comment by amezin** [comment] 2023-08-20 19:45
(mostly) fixed in `master` branch, will be available in the next release.

Better late than never

**Closed by amezin** 2023-08-20 19:45 UTC
Labels: bug
