### ISSUE TITLE
shortcut to switch to the other split term

### ISSUE THREAD

**Issue by squalou** [ddterm/gnome-shell-extension-ddterm#682] opened 2023-11-27 10:27 UTC
Maybe I'm missing something,

but I did not manage to change form one splitted view to the other using shortcuts.

(and I did not understand really the mix that happens when using both split view and multi tabs)

Using keyboard only navigation is really needed when using terminals.

kind regards,

**Comment by amezin** [comment] 2023-11-27 15:08
Duplicate of https://github.com/ddterm/gnome-shell-extension-ddterm/issues/645

Already implemented in https://github.com/ddterm/gnome-shell-extension-ddterm/commit/e05d4bb53dd50a969b151fe5163450c0f6e5fd79 but there has been no release yet

**Closed by amezin** 2023-11-27 15:08 UTC
Labels: enhancement

**Comment by RafalSkolasinski** [comment] 2024-02-13 10:53
Would be nice to have option to "switch to left pane" / "switch to right pane" - would be much more intuitive to add key bindings `alt+left` and `alt+right` - also it should not wraparound the panes. 

Is it worth it to open a specific issue on this @amezin?

---

Bonus question (can open another issue) - was it considered to add multi-pane split? Right now I think one can only split the terminal once.
