### ISSUE TITLE
Gnome 44

### ISSUE THREAD

**Issue by killown** [ddterm/gnome-shell-extension-ddterm#443] opened 2023-05-06 19:32 UTC
### GNOME Shell version

GNOME Shell 44.1

### Session type

Xorg

### Special configuration

- [ ] High DPI
- [X] More than one monitor

### ddterm version

44

### Linux distro

Arch Linux

### ddterm settings dump

[neo@archlinux ~]$ dconf dump /com/github/amezin/ddterm/
[/]
background-color='rgb(23,28,42)'
background-opacity=0.90000000000000002
bold-color-same-as-fg=true
command='custom-command'
custom-command='zsh'
custom-font='MonoLisa 12'
ddterm-toggle-hotkey=['F11']
detect-urls-voip=false
foreground-color='rgb(0xd0, 0xcf, 0xcc)'
panel-icon-type='toggle-button'
shortcuts-enabled=false
tab-position='top'
theme-variant='dark'
use-system-font=false
use-theme-colors=false
window-maximize=false
window-monitor='current'
window-monitor-connector='DisplayPort-0'
window-size=1.0

### Description

Dropdown not working, I can access the settings but only that. Tested with icon click and shortcut

**Comment by lfom** [comment] 2023-05-07 03:06
Error on Wayland:
```
gnome-shell[56251]: JS ERROR: TypeError: Object is of type Meta.LaunchContext - cannot convert to MetaContext
                                    spawn_app@/home/lfom/.local/share/gnome-shell/extensions/ddterm@amezin.github.com/extension.js:296:45
                                    activate@/home/lfom/.local/share/gnome-shell/extensions/ddterm@amezin.github.com/extension.js:346:9
                                    toggle@/home/lfom/.local/share/gnome-shell/extensions/ddterm@amezin.github.com/extension.js:329:9
                                    enable/<@/home/lfom/.local/share/gnome-shell/extensions/ddterm@amezin.github.com/extension.js:192:13
                                    set type/<@/home/lfom/.local/share/gnome-shell/extensions/ddterm@amezin.github.com/panelicon.js:218:22
                                    vfunc_event@/home/lfom/.local/share/gnome-shell/extensions/ddterm@amezin.github.com/panelicon.js:141:22

```

Reference for the version 12 of `Meta.WaylandClient.new()`:

https://gjs-docs.gnome.org/meta12~12/meta.waylandclient#constructor-new

Quick patch to fix the error while keeping compatibility with older versions:

```
wayland_client = Me.metadata.version > 43 ?
    Meta.WaylandClient.new(global.context, subprocess_launcher) : 
    Meta.WaylandClient.new(subprocess_launcher);
```

**Comment by somepaulo** [comment] 2023-05-09 09:12
> Quick patch

For me this doesn't work on GNOME 44.1 for some reason, but just adding `global.context, ` before `subprocess_launcher` on line `296` makes the extension work. Doesn't solve backwards compatibility though.

**Comment by lfom** [comment] 2023-05-09 15:43
Probably you didn't bump the extension version as well? This was not included in the patch.

**Comment by mjnaderi** [comment] 2023-05-10 15:15
The `master` branch is working correctly in Gnome 44.1.

**Comment by idoleat** [comment] 2023-05-11 03:54
Seems Gnome is aware that extensions can work without explicitly claiming support for new version of shell. There is an option `Disable version validation` in https://extensions.gnome.org/local/ which lets you ignore the version check. ddterms works after I enable that option.

**Comment by dragosprotung** [comment] 2023-05-11 08:02
Managed to make `master` branch work after changing several settings (settings window was working) to go around crashes like:

```
JS ERROR: TypeError: this.settings['custom-command'] is undefined
spawn@/home/dragos/.local/share/gnome-shell/extensions/ddterm@amezin.github.com/ddterm/app/terminalpage.js:702:17
new_page@/home/dragos/.local/share/gnome-shell/extensions/ddterm@amezin.github.com/ddterm/app/notebook.js:331:18
_init@/home/dragos/.local/share/gnome-shell/extensions/ddterm@amezin.github.com/ddterm/app/appwindow.js:287:27
...
```

```
JS ERROR: TypeError: invalid 'instanceof' operand type_resolved
set type_name@/home/dragos/.local/share/gnome-shell/extensions/ddterm@amezin.github.com/ddterm/shell/panelicon.js:238:17
createCheckedMethod/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:730:46
...
```

**Comment by peanutbudder** [comment] 2023-05-14 02:42
I can also confirm that building from source from the Master branch works on gdm 41-1.

**Comment by thacoon** [comment] 2023-05-14 13:15
Just build master and installed the extension on arch linux using latest gnome and gdm (v44.1-1) and everything seems to work fine.

**Comment by amezin** [comment] 2023-09-19 17:12
Another duplicate of https://github.com/ddterm/gnome-shell-extension-ddterm/issues/430

**Closed by amezin** 2023-09-19 17:12 UTC
Labels: bug
