### ISSUE TITLE
[feature] Option to control width

### ISSUE THREAD

**Issue by gersonjferreira** [ddterm/gnome-shell-extension-ddterm#982] opened 2024-07-04 03:10 UTC
The extension already has an option to control its height. Please add a similar option to control the width, keeping it centered on the screen.

**Comment by amezin** [comment] 2024-07-04 08:08
Duplicate of https://github.com/ddterm/gnome-shell-extension-ddterm/issues/129

**Closed by amezin** 2024-07-04 08:08 UTC
Labels: enhancement
